name: Bench

on:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update local toolchain
        run: |
          rustup update
          rustup install nightly
          rustup default nightly
          rustup component add clippy
          rustup component add rustfmt

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

      - name: Bench
        run: |
          cargo bench
